### ISSUE TITLE
Error: index out of bounds

### ISSUE THREAD

**Issue by thomtro** [blaa/fuzzdex#1]
I was happy to find fuzzdex, as I try to identify word lemmas in older text with lots of spelling variation.
Unfortunately, I got stuck. My code seems to work, but index searches only work about 1 out 10 times.
The remaining attempts fail, with error messages like this;

> pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1

The trouble-making line: print(former1.search("abbeddom", [], max_distance=3, limit=10))

Any help is much appreciated.

Thomas

**Comment by blaa** [comment]
Hello,
  I'll happily help but I need to reproduce the bug. Is the code generating former1 very complicated? Could you create a small test-case that causes the problem to appear? Even in 1/10 runs. I haven't used max_distance larger than 2 so far, so I guess the bug might be somewhere there.

Also this seems to be a Python-glue code, not a rust error. Maybe it's just handling of the result that needs fixing.

I'll have some time tomorrow to look into this.

**Comment by blaa** [comment]
I assume you're using 0.6.1, with which python version? 

I'm trying to build a failing example based on:
```
import fuzzdex
cities = fuzzdex.FuzzDex()
cities.add_phrase("abbedom", 1, constraints=set())
cities.add_phrase("abedom", 2, constraints=set())
cities.finish()
cities.search("abbe", [], max_distance=3, limit=10)
```

Can't fail it yet.

**Comment by blaa** [comment]
Having no feedback and being unable to reproduce I'll close this issue. 

I tried setting up a fuzzer, but that's probably some API problem, not really a data one. Although I suspected some differences in unicode handling between python and rust. Can't reproduce it without your data. ;s

**Comment by thomtro** [comment]
Hello again

I'm new to Github, so perhaps my feedback (see below+attachment) went to 
a wrong mail address, sorry!

In the meantime, I found out that I can probably use rapidfuzz 
(process.extract) instead to achieve my goal, so you don't have to worry 
for my sake.

Regards,
Thomas



-------- Videresendt meddelelse --------
Emne: 	Re: [blaa/fuzzdex] Error: index out of bounds (Issue #1)
Dato: 	Sun, 2 Oct 2022 09:40:07 +0200
Fra: 	Thomas Troelsgård ***@***.***>
Svar-Til: 	***@***.***
Til: 	Tomasz bla Fortuna ***@***.***>



Thanks for your quick reply!

I tried to scale down the number of lines in the index, and it then 
seems to work.
My problem is that I need to search millions of records...

When I increase the number, it starts failing again:

thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but 
the index is 1', src/fuzzdex.rs:324:31
note: run with `RUST_BACKTRACE=1` environment variable to display a 
backtrace
Traceback (most recent call last):
   File "ren_test_netto.py", line 55, in <module>
     print(former.search("abbetissa", [], max_distance=10, limit=20))
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the 
index is 1

I attach my script and the text file used for building the index (in a 
shortened version).


Regards
Thomas


Den 01.10.2022 kl. 22.39 skrev Tomasz bla Fortuna:

**Comment by blaa** [comment]
Thanks! This error pinpoints the issue way better. Rerunning with RUST_BACKTRACE=1 would be even better.

Well, I'd like to make it better, for yours sake or otherwise. ;) So thanks for feedback, it initially really went missing (I don't have it on email either).

**Comment by blaa** [comment]
Ok, so the problem was you've added multiple phrases with the same phrase_idx, which on querying caused an error. phrase_idx has to be unique. The API didn't check for it or enforce it and I'll fix that. Also I've made it work better with long phrases (documents - unsure if it makes sense to use like that) and fixed a potential DoS with a very long tokens.

**Comment by blaa** [comment]
Now the Python interface raises RuntimeError in this case, and Rust has a different API which returns Result<>. I still have to publish it - it will be 0.7 or something newer.
